### ISSUE TITLE
put credits below the definition in the lexicon output

### ISSUE THREAD

**Issue by balmas** [alpheios-project/lexsvc#3]
E.g. the "From Lewis and Short..."  It should appear once at the bottom of all definitions. (And needs to include date, etc.)

**Comment by balmas** [comment]
this should be fixed now. It's not really possible to aggregate and present a single credits line, because each definition is the result of a separate service call which returns HTML and it is possible that these could come from different lexicons.  Deduping and aggregating this information would be difficult with the current service.  It will have to wait for redesign of the service.

**Comment by monzug** [comment]
Can we add a line before the credits? just saying...

l. c., B.5.113, metri gr.; also Theoc.20.12, A.R.1.1271.]
From A Greek-English Lexicon (Henry George Liddell, Robert Scott, Oxford, Clarendon Press, 1940)

συν-εχής (ἔχω): neut. as adv., σῡνεχές, continuously, Il. 12.26; w. αἰεί, Od. 9.74.
From A Homeric Dictionary (Georg Autenrieth, New York, Harper and Brothers, 1891)

συνεχής 1συνέχω
0.holding together:
I.of space, continuous, contiguous, Thuc., Plat.:—c. dat. continuous with or contiguous to, in a line with, Hdt., Eur.
II.of Time, continuous, unintermitting, Xen.; τὸ ξυνεχές ῀ συνέχεια, Thuc.
III.of persons, constant, persevering, Xen.
B.adv. σῠνεχῶς, ionic -έως:
1.of Time, continually, Hes.; Sup. -έσταταXen.
2.with Numbers, continuously, Ar., Thuc.
II.in epic συνεχές as adv., Il.; συνεχὲς αἰείunceasing ever, Od.
σῡνεχέςHom., and σῡνεχέωςHes., the first syll. being lengthd.

1 συνεχής, ές
From An Intermediate Greek-English Lexicon (Henry George Liddell, Robert Scott, Oxford, Clarendon Press, 1889)

**Comment by balmas** [comment]
Yes I will do that. Thank you!

**Comment by balmas** [comment]
Need to give you a new build of the webextension to test this still...

**Comment by monzug** [comment]
thanks!
